# Licensed to Cloudkick, Inc under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# Cloudkick licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import("env extern")

lenv = env.Clone()

sources = Split("""
  ckl.c
  script.c
  transport.c
  conf.c
  editor.c
  msg.c
  util.c
""")

lenv.AppendUnique(LIBS=[extern['liboauth']])
ckl = lenv.Program("ckl", source=sources)

#TODO: don't repeat this
sources = Split("""
  ck_motd.c
  script.c
  transport.c
  conf.c
  editor.c
  msg.c
  util.c
""")

ck_motd = lenv.Program("ck_motd", source=sources)

targets = [ckl, ck_motd]

Return("targets")
